hashicorp/vault-action

.github/workflows/build.yml
dist/index.js
integrationTests/e2e-tls/e2e-tls.test.js
integrationTests/e2e-tls/setup.js
src/action.js

A bug with `tlsSkipVerify` introduced in #97 wouldn't allow users to disable the verification of Vault's certificate.  This fixes that bug and adds missing test coverage on this parameter which would have caught this bug.

Fix bug with tlsSkipVerify and add test coverage

---

.github/workflows/build.yml
README.md
action.yml
dist/index.js
integrationTests/basic/integration.test.js
integrationTests/enterprise/enterprise.test.js
src/action.js
src/secrets.js

This makes a backwards incompatible change to the UX for requesting secrets from Vault.  Changing the UX in a required way is not something I take lightly but I believe now is the best time to get this right.
This change makes requesting secrets more explicit by requiring the full path of the secret, rather than configuring extra parameters such as `path` and `kv-version`.  By being more explicit with the secret path, mixing secret engines is possible and there are less parameters to configure.
Additionally I added a bit of logic to unpack responses from Vault data smarter (instead of relying on parameters to change the selector logic).
New UX:
```yaml
- name: Import Secrets
uses: hashicorp/vault-action
with:
url: https://vault.mycompany.com:8200
token: ${{ secrets.VaultToken }}
secrets: …
```

Simplify secret request UX

---

.github/workflows/jira.yaml

These versions bring a few fixes:
* The action now supports converting the most common bits of markdown syntax into Jira formatting directives
* Replaces Atlassian's comment action, which tries to interpolate bits of text from comments wrapped in {{ github.event_name }} as templates, usually causing an error (in the case I've put there, if I wasn't a vault team member, it would replace the template with `pull_request_target`)
* Remove trailing comma after link that broke the link target Jira selects

Update Jira sync action versions

---

README.md

Without specifying `@v2.0.0` GitHub says the string is not the correct format
``` 
The workflow is not valid. .github/workflows/integration_tests.yml (Line: 10, Col: 15): Expected format {org}/{repo}[/path]@ref. Actual 'hashicorp/vault-action',Input string was not in a correct format.
```

specify version

---

README.md
action.yml
dist/index.js
integrationTests/basic/integration.test.js
src/action.js
src/action.test.js
src/secrets.js

Usefull when run terraform, packer etc ... in a workflow and want to use directly Vault token.

Add ability to export Vault Token

---

README.md

The auto-generated GH token on repositories does not work with Vault GH auth due to the lack of organization permissions. Adding a note about this in the README to clear up the confusion.

Add GitHub authentication notice

---

package-lock.json

Security dependencies issue for marked 1.0.0 versions. 
[Link](https://snyk.io/vuln/SNYK-JS-MARKED-1070800) is available here

chore(deps): bump marked from 1.2.6 to 2.0.1 security reason

---

README.md
action.yml
src/action.js
src/auth.js
src/auth.test.js

Built from https://github.com/hashicorp/vault-action/pull/155. Thanks to jojo19893  for most of the work.
This adds support for Kubernetes based auth (https://www.vaultproject.io/docs/auth/kubernetes).  It also adds a parameter to customize the path for any auth method.

Implement kubernetes auth / Add customizable auth path

---

CHANGELOG.md
README.md
dist/index.js

Features:
* K8s auth method is now supported [GH-218](https://github.com/hashicorp/vault-action/pull/218)
* Custom auth method mount points is configurable [GH-218](https://github.com/hashicorp/vault-action/pull/218)

Update to v2.3.0

---

.github/workflows/build.yml
docker-compose.yml

Since `hashicorp/vault-enterprise:latest` now requires a license to do
anything, we need to set `$VAULT_LICENSE` when provisioning the
enterprise docker container.

set vault license for enterprise tests

---

README.md

The Sample code provided in the readme doesn't work as expected unless the version has been updated to 2.4.0.

Updated the version in Readme doc.

---

.github/workflows/build.yml
integrationTests/basic/integration.test.js
integrationTests/basic/jwt_auth.test.js
integrationTests/enterprise/enterprise.test.js
src/action.test.js
src/auth.test.js

#294 upgraded a major jest-when version, which makes `when` a little more strict about requiring all the arguments to be specified: https://github.com/timkindberg/jest-when/releases/tag/v3.0.0
I hadn't realised the tests are run against `pull_request_target` in the CI, so they only failed once merged to master. This PR fixes them up, but suffers from the same `pull_request_target` problem, so I've also added a `workflow_dispatch` trigger, and triggered the tests manually:
```bash
gh workflow run build.yml --ref fix-tests
✓ Created workflow_dispatch event for build.yml at fix-tests
```
Passing test results here: https://github.com/hashicorp/vault-action/actions/runs/2227014792

Fix tests from jest-when version bump

---

CHANGELOG.md
package-lock.json
package.json
src/action.js
src/action.test.js
src/retries.test.js

Fixes #332 - see issue for details.
412 means the token used has not yet been replicated to the performance replica queried, so we can append it to the list of retryable HTTP codes.

Retry on 412 status codes

---

action.yml

Addresses #373 
The PR sets `node16` as a runtime in the action.yaml file.
This version is already being used for [building and testing the action](https://github.com/hashicorp/vault-action/blob/main/.github/workflows/build.yml#L17) thus the change shouldn't have any side effects 
[GitHub Actions: All Actions will begin running on Node16 instead of Node12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)
> We plan to migrate all actions to run on Node16 by Summer 2023. We will monitor the progress of the migration and listen to the community for how things are going before we define a final date.
To raise awareness of the upcoming change, we are adding a warning into workflows which contain Actions running on Node 12. …

use node16 for the action

---

README.md

So we don't have to keep remembering to update the version tag in the readme.
Related to #263

change example to `vault-action@v2`

---

CHANGELOG.md
dist/index.js

This is the patch release of Vault Action with updated dependencies. The most notable change coming from https://github.com/hashicorp/vault-action/pull/375, which sets `node16` as the runtime in the `action.yaml` file.

Update to v2.4.3

---

action.yml
dist/index.js
src/action.js
src/action.test.js

Adds support for encoded Vault secrets.
Example usage:
```
with:
namespace: ${{ secrets.VAULT_NAMESPACE }}
url: ${{ secrets.VAULT_ADDR }}
method: token
token: ${{ secrets.VAULT_TOKEN }}
tlsSkipVerify: false
secretEncoding: "hex"
secrets: |
kv/test foohex | FOOHEX;
```
Resolves #105

Add Decoding to Secrets

---

dist/index.js
package-lock.json
package.json
src/auth.js

similar to #276, but you dont need to enable debug logging
closes #273 
also changes ncc to vercel/ncc

print vault error message on authentication failure

---

package-lock.json
package.json

This PR removes unused devDependencies from the `package.json` file. After merging a dev dependency update for semantic-release in https://github.com/hashicorp/vault-action/pull/415, I realized that it requires using node >= 18. Currently, this project uses [node 16](https://github.com/hashicorp/vault-action/blob/main/action.yml#L83). This caused me to look closer into how these devDependencies are used. 
I'm quite sure we're not using semantic-release. I could use someone to confirm this for me. If we're not using it, I wonder if we can remove [these lines](https://github.com/hashicorp/vault-action/blob/main/package.json#L18-L27) from the `package.json` file?
The [depcheck](https://www.npmjs.com/package/depcheck) tool produced this list of unused devDependencies:
```sh
$ depcheck …
```

Removes unused devDependencies from package.json

---

.github/workflows/build.yml
.github/workflows/local-test.yaml
README.md
integrationTests/basic/integration.test.js
integrationTests/basic/jwt_auth.test.js
integrationTests/e2e/setup.js
integrationTests/enterprise/enterprise.test.js

+ added a contribution section to the README
+ added a local workflow to help test changes
+ made the vault token configurable for tests so people can run acc tests against their already-running vault instance
+ bumped the action/checkout version, 
+ use the ref param to checkout the branch that created the event so the acceptance tests use the PR code and not the default branch, I believe at the moment this is causing the CI checks to pass even if the code introduces regressions

Development flow enhancements

---

src/secrets.js

Handle errors without a response property.  Testing against a vault with self signed certs w/out providing the `caCertificate` input.
Before:
After:

Handle undefined response in getSecrets error handler

---

README.md
integrationTests/e2e/setup.js

+ added documentation on how to use the retrieved secrets
+ added an example of converting the vault-action outputs to json
Consuming vault-action output as a json file originally requested is this issue: #98 
After discussion it was proposed to not add this responsibility to the vault-action itself but document how it can be done using the GHA tools readily available.

Enhanced "Example Usage" section

---

CHANGELOG.md
action.yml
integrationTests/basic/approle_auth.test.js
integrationTests/basic/userpass_auth.test.js
src/action.js
src/auth.js

PR helps in appending /{username} at last after /login in path while calling vault auth API.
Related and fixes https://github.com/hashicorp/vault-action/issues/433
Added approle test which can now run as part of not just in basic integration suite instead of enterprise alone
Please review and let me know if I need to code it differently since I am not super familiar with nodejs.
Let me know If you need me to add changelog, it had pull request ids so thought you might add at later stage

feat(auth): adding userpass and ldap auth

---

CHANGELOG.md
src/entry.js

In the event vault-action throws an error, the error message is sent to the workflow log when with `core.setFailed`, but that output is not accessible to other steps in the workflow.
This change sets an output for the error message, called errorMessage, than can be read by other steps within the workflow and parsed.

Set output for the error message

---

README.md

Documentation improvement to address #153 
The problem mentioned cannot be reproduced anymore, keys with dashes work as expected as was tested [when writing this comment](https://github.com/hashicorp/vault-action/issues/153#issuecomment-1452578840). An [acceptance test also covers this use case](https://github.com/hashicorp/vault-action/blob/main/integrationTests/basic/integration.test.js#L41) to prevent regressions.

Document that the selector uses JSONata

---

.github/workflows/build.yml

Vault Action builds have only been running against the main branch since forever? So PRs are not having any of the tests run against the PR branches code. Also don't reuse step IDs.

ensure we run the build for all branches

---

.github/workflows/build.yml
integrationTests/e2e/e2e.test.js
integrationTests/e2e/setup.js

This reverts commit d27529ebdeec73e7347123218eca231e751860c5 until we can determine the cause of the failure.
See details in #350 and #453

Revert "Test that overwrite env var works in nested action (#453)"

---

integrationTests/e2e/e2e.test.js
src/action.test.js
src/secrets.js

This change will revert to the behavior vault-action has exhibited [since v2.1.2](https://github.com/hashicorp/vault-action/commit/5e5c06a3c8e96b7c4757fe7a10e03469cdbd07bb#diff-3d2b59189eeedc2d428ddd632e97658fe310f587f7cb63b01f9b98ffc11c0197R10775). This ensure that all JSON is valid when set as an environment variable and that step output will be a JSON object. 
I can't find the source code of github actions to actually verify this, but it seems to me that when the step output is passed to another action using the `with` keyword, the github action framework actually `JSON.stringify`'s the data. This means that anything that accepts a Vault secret as input will have a valid JSON string that can then be `JSON.parse`'d. For example, this allows the following to work:
```
- name: …
```

revert fix secrets stored in JSON format (#473)

---

README.md
action.yml

The PR updates the README to be more read-(me)-able. This should also allow linking directly to the documentation for specific fields. Additionally, make some clarifications for `caCertificate`.
Closes #452

chore: update readme reference for readability

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md

Prepare for v2.7.4 release.
Additionally, we update the
- PR template to include a checklist for
- changelog entries and
- a reminder to not commit to `dist/index.js` for non-release PRs
- Improvements to the bug and feature request templates

Update to v2.7.4

---

CHANGELOG.md
action.yml

Node 16 has reached its end of life
More details here: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

Use nodejs 20

---

CHANGELOG.md
README.md
action.yml
integrationTests/basic/integration.test.js
src/secrets.js

Add `ignoreNotFound` input (default: false) to prevent the action from failing when a secret does not exist
Supercedes #506 

feature: add ignoreNotFound option

---

.github/workflows/build.yml
.github/workflows/local-test.yaml
CHANGELOG.md
action.yml

This reverts [GH-509](https://github.com/hashicorp/vault-action/pull/509) which made a backwards incompatible bump of the node runtime from node16 to node20 [GH-524](https://github.com/hashicorp/vault-action/pull/524). In particular, Github Enterprise does not support node20 at this time.
closes #526 
We plan to issue a v3 release with the node20 runtime.

Prepare for v2.8.1 release

---

.github/workflows/build.yml
.github/workflows/local-test.yaml
CHANGELOG.md
action.yml

Bump the node runtime from node16 to node20 which calls for a major version bump of the action from v2 to v3.
This is a follow up to https://github.com/hashicorp/vault-action/pull/527.

Prepare for v3.0.0 release

---

CHANGELOG.md
src/auth.js

`secretId` is no longer required for approle to support advanced use cases like machine login when `bind_secret_id` is false.
Closes #520 

approle: do not require secret_id

---

CHANGELOG.md
dist/index.js
integrationTests/basic/integration.test.js
src/secrets.js

fix wildcard handling when field contains dot

---

README.md
integrationTests/basic/jwt_auth.test.js

Closes https://github.com/hashicorp/vault-action/issues/559
the tests were failing due to the jwt auth's recent behavior change in 1.17 so that is fixed here as well. See https://developer.hashicorp.com/vault/docs/upgrading/upgrade-to-1.17.x#jwt-auth-login-requires-bound-audiences-on-the-role

docs: add namespace example to readme

---

CHANGELOG.md
README.md
action.yml
integrationTests/basic/integration.test.js
src/action.js
src/index.js
src/pki.js

Add the ability to generate PKI certificates from Vault's PKI engine. You can now use the `pki` option to generate a certificate and private key for a given role.
````yaml
with:
pki: |
pki/issue/rolename {"common_name": "role.mydomain.com", "ttl": "1h"} ;
pki/issue/otherrole {"common_name": "otherrole.mydomain.com", "ttl": "1h"} ;
```
Resulting in:
```bash
ROLENAME_CA=-----BEGIN CERTIFICATE-----...
ROLENAME_CERT=-----BEGIN CERTIFICATE-----...
ROLENAME_KEY=-----BEGIN RSA PRIVATE KEY-----...
ROLENAME_CA_CHAIN=-----BEGIN CERTIFICATE-----...
OTHERROLE_CA=-----BEGIN CERTIFICATE-----...
OTHERROLE_CERT=-----BEGIN CERTIFICATE-----...
OTHERROLE_KEY=-----BEGIN RSA PRIVATE KEY-----...
OTHERROLE_CA_CHAIN=-----BEGIN CERTIFICATE-----...
```` …

feat: Add PKI capability

---

dist/index.js

Update the build output file with the latest changes
Relates OR Closes #0000

chore: Update dist/index for latest code

---

CHANGELOG.md
package-lock.json

Updates dependencies to prepare for release

Prepare for v3.1.0 release

---

dist/index.js
src/auth.js
src/auth.test.js

core.getIDToken intermittently fails for both cloud hosted and on prem runners. This causes entire workflows to fail.
Adds a generic async retry function. Adds 5 retries with 3 seconds of delay between core.getIDToken calls.
Closes #525

Retry core.getIDToken for JWT Auth Method

---

.github/workflows/actionlint.yaml
.github/workflows/build.yml
.github/workflows/local-test.yaml
CHANGELOG.md

Prep for v3.2.0 release
- Update changelog
- Bump GHA's
```
tsccr-helper gha update .github/workflows/
```

Prepare for v3.2.0 release

---

CHANGELOG.md
README.md
dist/index.js
integrationTests/basic/integration.test.js
src/action.js
src/constants.js
src/secrets.js
src/utils.js

When using the wildcard to match multiple secrets to export as env variables, all keys get uppercased. There are situations where this is undesirable. To maintain backwards compatibility I've added an alterative double asterisk `**` which will avoid uppercasing exported env keys.
Relates https://github.com/hashicorp/vault-action/pull/537
Closes https://github.com/hashicorp/vault-action/issues/536

feat: added double asterisk wildcard selector to prevent uppercasing of keys before exporting envs
