.github/workflows/build.yml
action.yml
dist/index.js
package-lock.json
package.json

fix: package action

---

.github/workflows/build.yml
README.md
action.js
action.test.js
dist/index.js
integrationTests/basic/integration.test.js
integrationTests/e2e/e2e.test.js
integrationTests/e2e/setup.js
integrationTests/enterprise/enterprise.test.js

Sharing two features I required for my setup. 
Docs and tests are included, but feel free to adapt as you see fit.
Hope it helps! :slightly_smiling_face:

feat: support for KV version 1 and custom-named engines

---

action.js
action.test.js
action.yml
dist/index.js

Adds the ability to set extra headers on every vault request.

feat: add the ability to set extra headers

---

README.md

Small documentation update to add TLS parameters.

Update doc for TLS

---

.github/workflows/jira.yaml

This adds the Jira sync workflow to the repository, as taken from https://github.com/hashicorp/.github, with team set to ecosystem.

Add Jira sync workflow

---

package-lock.json

dep: update jsonata to version 1.8.3

---

package-lock.json
package.json

Closes #65 
Closes #69 
Closes #71 
Closes #79

dep: update dev dependencies

---

CHANGELOG.md
dist/index.js

This is the minor release of Vault Action with updated dependencies.

Update to v2.0.1

---

dist/index.js

This PR updates Vault Action packages to their latest available versions. Most importantly `actions/core` was updated to `1.2.6` to address a minor CVE: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/. Updated here: https://github.com/hashicorp/vault-action/pull/130.
Fixes #131

Update to v2.0.2

---

package-lock.json
package.json

Reverts hashicorp/vault-action#147 which is causing build errors.

Revert "chore(deps-dev): bump jest-when from 2.7.2 to 3.0.1"

---

README.md

Modify the README to include the newest version of the action

bump readme to action v2.1.0

---

CHANGELOG.md
README.md
dist/index.js

This is a minor update to Vault Action to bump some dependencies. No new features are available in this release.

Update to v2.1.1

---

src/secrets.js

Not sure if this is the right solution. But it seems to work in tests I've made.

Support complex keys, such as yaml/json files

---

CHANGELOG.md
README.md
dist/index.js

* fixed bug where newlines were being rendered for multi-line secrets [GH-173](https://github.com/hashicorp/vault-action/pull/173)

Update to v2.1.2

---

README.md

Missed a version in the README for the v2.2.0 update.

Update version in example doc

---

CHANGELOG.md
README.md
dist/index.js

A minor release of this action with updated dependencies.

Update to v2.3.1

---

integrationTests/basic/integration.test.js
src/secrets.js

This replaces https://github.com/hashicorp/vault-action/pull/182 so that we can address additional follow-up comments.

Write a better error message when secret not found (follow-up)

---

CHANGELOG.md
dist/index.js

Prepare to release v2.4.1
Manual CI run against this commit: https://github.com/hashicorp/vault-action/actions/runs/2238740072

Update to v2.4.1

---

.github/workflows/build.yml
package-lock.json

Bug is here: https://github.com/npm/cli/issues/4660
Tests passed here: https://github.com/hashicorp/vault-action/runs/6908644514

Freeze node/npm version to work around package-lock bug

---

CHANGELOG.md
package-lock.json
package.json

Bumps `got` to the latest version within our current major version.

Bump got to 11.8.5

---

.github/workflows/jira.yaml

Updating the team tag from foundations --> applications

jira-sync: update the team to applications

---

README.md

I forgot to commit the readme.
https://github.com/hashicorp/vault-action/pull/440

chore(readme): adding readme for #440

---

.github/workflows/jira.yaml

Migrate to workflows-common
Closes #454

Update Jira workflow

---

action.yml

Closes https://github.com/hashicorp/vault-action/issues/460

fix warning about outputToken being an unexpected input

---

package.json

Updates the Vault Action name to Vault in the GH Marketplace

Update Vault Action name in package.json

---

package.json

Reverts hashicorp/vault-action#493

Revert "Update Vault Action name in package.json"

---

action.yml

This PR changes the action name in the GH marketplace from "Vault Secrets" to "HashiCorp Vault"

action: update marketplace name

---

README.md

Add an example to the documentation using the path parameter.

Add path parameter example

---

CHANGELOG.md
dist/index.js

Update to v2.7.5

---

CHANGELOG.md

fix changelog link

---

README.md

chore: add details on kvv2 path to README

---

.github/workflows/build.yml
Makefile
README.md

This PR updates the docker compose command to use the non-hyphenated version. The new command is required by v2 of docker compose.
ref: https://docs.docker.com/compose/releases/migrate/#what-are-the-differences-between-compose-v1-and-compose-v2

chore: Update docker compose command

---

CHANGELOG.md
dist/index.js
integrationTests/basic/integration.test.js
src/utils.js

fix: replace all dot chars during normalization
